matrix:
    include:
        - language: node_js
          node_js:
              - "11"
          before_script:
              - npm i
          script:
              - npm test
              - npm coverage